FROM public.ecr.aws/lambda/nodejs:20

WORKDIR /var/task

# Production environment
ENV NODE_ENV=production

# Install only production dependencies
COPY package*.json ./
RUN npm ci --omit=dev

# Copy source code
COPY . .

# Lambda entry point
CMD ["src/lambda.handler"]
